version = 5.5.0
archive_dir = /etc/letsencrypt/archive/dummy.bolbolanon.help
cert = /etc/letsencrypt/live/dummy.bolbolanon.help/cert.pem
privkey = /etc/letsencrypt/live/dummy.bolbolanon.help/privkey.pem
chain = /etc/letsencrypt/live/dummy.bolbolanon.help/chain.pem
fullchain = /etc/letsencrypt/live/dummy.bolbolanon.help/fullchain.pem
[renewalparams]
account = dd20251b75ada3d26b7fa87c7e072ff3
rsa_key_size = 2048
key_type = rsa
pref_challs = dns-01,
authenticator = manual
manual_auth_hook = acme-dns-client
server = https://acme-v02.api.letsencrypt.org/directory
renew_hook = true
