version = 5.5.0
archive_dir = /etc/letsencrypt/archive/global.bolbolanon.help
cert = /etc/letsencrypt/live/global.bolbolanon.help/cert.pem
privkey = /etc/letsencrypt/live/global.bolbolanon.help/privkey.pem
chain = /etc/letsencrypt/live/global.bolbolanon.help/chain.pem
fullchain = /etc/letsencrypt/live/global.bolbolanon.help/fullchain.pem
[renewalparams]
account = dd20251b75ada3d26b7fa87c7e072ff3
pref_challs = dns-01,
server = https://acme-v02.api.letsencrypt.org/directory
authenticator = manual
manual_auth_hook = acme-dns-client
key_type = ecdsa
[acme_renewal_info]
ari_retry_after = 2026-04-28T12:30:45
